language: python
python:
- '3.6'
services:
- postgresql
addons:
  postgresql: "9.4"
  sauce_connect: true
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
install:
- pip install -r requirements.txt
script:
- python manage.py test
