language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U dbadmin

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
