dist: trusty
language: python
python:
- '3.6'
services:
- postgresql
sudo: required
addons:
  postgresql: '9.4'
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
install:
- pip install -r requirements.txt
script:
- whereis google-chrome-stable
- whereis chromedriver
- python manage.py test
notifications:
  slack:
    secure: ccWJaX2Y8iFVA/rS3pmQ9EXg92Ag4UA+ttmQd3Q7NYhW3GB/Ckw/SZcUYt5++7fJipQ9iH/2fvek/8rLK/kUSXVSqXDfrvsvcbcFhdCMLUFWphw40DpnmeeG1YsFZXKf2PUEGj/q9p635Ft0n8pAqcWdLGLufJPr7IUonLa5iHqq49FLVJQejQ7aY1xmf/4VTOd+DyR+mvpxRzaKD2SkxERNOukg0mgIrQcUhb6p7tJD2r+Cg4BzrO1z+vWhyQigPaqoasVh9H0GV3zZOy+0zJHnUKEIN1lWVi5N00SZuxWY+JgqAGiyl/lyu83A2TjBQgfCqiR957n8N0ClAIbY1No/TL3PuJqoxCnuiEte+F4yau2knM8UvsW0jrHLzzRmJ6po0A6zLooLRGRQdBNOJ5dPvbL3INNDXjyYWZ1Fwcq1rjPQ/5PAOL37hz3PnG0+qrNllr7ibLA9hM2GohhTHSxeDJRZFjtCovNClgZcskcXVIkPw/+26119ZvJJ+t9xh1SkrvSXpBFbQStd8En5nc9JIizPzc+Mei8Z8rqcbPZqLMR9C//OwNOCASpYgEpTcaIjfXmpxdtEVRIf/roElBpoRBHPb3yCxHm6HwyKc4eivEKHJc1SynA+LlII8Z3fWYeRaUWh8X28A9HjXg/pEaHPONBDtgGkU8QIIeSij80=
