# Generated by Django 2.1 on 2018-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
