# Generated by Django 2.1 on 2018-09-17 19:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180912_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
