# Generated by Django 2.1.2 on 2018-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_portfolio_benchmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='benchmark',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='benchmark_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='benchmark_ticker',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Benchmark',
        ),
    ]
