# Generated by Django 2.1.2 on 2019-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190810_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='logo_url',
            field=models.URLField(default='https://www.fillmurray.com/200/300'),
        ),
    ]
