# Generated by Django 2.1.2 on 2019-10-03 00:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ticker_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='benchmark_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='historical_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
