# Generated by Django 2.1.2 on 2019-10-03 00:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191003_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='benchmark_name',
            field=models.CharField(default='S&P 500 Vanguard', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='benchmark_ticker',
            field=models.CharField(max_length=5, null='voo'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
