# Generated by Django 2.2.10 on 2020-03-30 20:27

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20191003_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iex_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='benchmark_name',
            field=models.CharField(default='Vanguard S&P 500', max_length=200),
        ),
    ]
