# Generated by Django 2.2.10 on 2020-04-12 14:14
from django.contrib.postgres.operations import CryptoExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_profile_dark_mode'),
    ]

    operations = [
        CryptoExtension(),
        migrations.AddField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='cik',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='entity_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='figi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='provider_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='reference_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
