# Generated by Django 2.2.10 on 2020-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200413_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='cik',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='entity_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='figi',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='provider_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
