# Generated by Django 2.2.10 on 2020-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200413_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='palette',
            field=models.TextField(choices=[('dark_knight', 'Dark Knight'), ('ice_man', 'Ice Man'), ('bright_eyes', 'Bright Eyes')], default='dark_knight'),
        ),
    ]
