# Generated by Django 2.2.10 on 2020-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200504_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='cik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
