# Generated by Django 3.1.2 on 2020-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20201230_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
