# Generated by Django 3.1.2 on 2021-05-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210214_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='target_return',
            field=models.FloatField(null=True),
        ),
    ]
